version: 0.2
 
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - apt-get install -y unzip

  build:
    commands:
      - echo Build started on `date`
      - zip hello.zip ./index.html /opt/codedeploy-agent/deployment-root/08ba87a4-118e-466f-a780-69e067f35277/d-3CU4PZL80/deployment-archive 
      - mv ./appspec.html ./opt/codedeploy-agent/deployment-root/08ba87a4-118e-466f-a780-69e067f35277/d-3CU4PZL80/deployment-archive
   
artifacts:
  type: 
  files:
    - index.html
